<?php

/**
 * Baseefipp3empleado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $dni
 * 
 * @method string         getName() Returns the current record's "name" value
 * @method integer        getDni()  Returns the current record's "dni" value
 * @method efipp3empleado setName() Sets the current record's "name" value
 * @method efipp3empleado setDni()  Sets the current record's "dni" value
 * 
 * @package    efipp3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseefipp3empleado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('efipp3empleado');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('dni', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}