<?php

/**
 * Baseefipp3automovil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $modelo
 * @property efipp3cliente $efipp3cliente
 * 
 * @method string          getName()          Returns the current record's "name" value
 * @method string          getModelo()        Returns the current record's "modelo" value
 * @method efipp3cliente   getEfipp3cliente() Returns the current record's "efipp3cliente" value
 * @method efipp3automovil setName()          Sets the current record's "name" value
 * @method efipp3automovil setModelo()        Sets the current record's "modelo" value
 * @method efipp3automovil setEfipp3cliente() Sets the current record's "efipp3cliente" value
 * 
 * @package    efipp3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseefipp3automovil extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('efipp3automovil');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('modelo', 'string', 225, array(
             'type' => 'string',
             'length' => 225,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('efipp3cliente', array(
             'local' => 'cliente_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}