<?php

/**
 * Baseefipp3cliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $dni
 * @property string $domicilio
 * @property Doctrine_Collection $efipp3automovil
 * @property Doctrine_Collection $efipp3turno
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method integer             getDni()             Returns the current record's "dni" value
 * @method string              getDomicilio()       Returns the current record's "domicilio" value
 * @method Doctrine_Collection getEfipp3automovil() Returns the current record's "efipp3automovil" collection
 * @method Doctrine_Collection getEfipp3turno()     Returns the current record's "efipp3turno" collection
 * @method efipp3cliente       setName()            Sets the current record's "name" value
 * @method efipp3cliente       setDni()             Sets the current record's "dni" value
 * @method efipp3cliente       setDomicilio()       Sets the current record's "domicilio" value
 * @method efipp3cliente       setEfipp3automovil() Sets the current record's "efipp3automovil" collection
 * @method efipp3cliente       setEfipp3turno()     Sets the current record's "efipp3turno" collection
 * 
 * @package    efipp3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseefipp3cliente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('efipp3cliente');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('dni', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
        $this->hasColumn('domicilio', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('efipp3automovil', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('efipp3turno', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}