<?php

/**
 * Baseefipp3reparacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $costo
 * @property Doctrine_Collection $efipp3turno
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method integer             getCosto()       Returns the current record's "costo" value
 * @method Doctrine_Collection getEfipp3turno() Returns the current record's "efipp3turno" collection
 * @method efipp3reparacion    setName()        Sets the current record's "name" value
 * @method efipp3reparacion    setCosto()       Sets the current record's "costo" value
 * @method efipp3reparacion    setEfipp3turno() Sets the current record's "efipp3turno" collection
 * 
 * @package    efipp3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseefipp3reparacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('efipp3reparacion');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('costo', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('efipp3turno', array(
             'local' => 'id',
             'foreign' => 'reparacion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}