<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/08/15 01:01:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=efipp3',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
