<?php

/**
 * efipp3turnoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class efipp3turnoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object efipp3turnoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('efipp3turno');
    }
}