<?php

/**
 * efipp3automovilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class efipp3automovilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object efipp3automovilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('efipp3automovil');
    }
}