<?php

/**
 * efipp3empleadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class efipp3empleadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object efipp3empleadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('efipp3empleado');
    }
}