<?php

/**
 * efipp3reparacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class efipp3reparacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object efipp3reparacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('efipp3reparacion');
    }
}