<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/08/15 15:15:28

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=efisymfony',
  'username' => 'root',
  'password' => 'colo',
  'name' => 'doctrine',
)),);
